### ISSUE TITLE
Not able to add the Swift Package manager in Xocde - 12.4

### ISSUE THREAD

**Issue by SreekanthGudisi** [enparadigm/SharpsellCore#1]
Hi, 

I'm trying to add https://github.com/enparadigm/SharpsellCore to the Swift Package manager but it's giving the below screenshot error. 

Should I use XCode - 13 for installing SharpsellCore? 

Is any Possible to add in XCode - 12.4? if yes please guide me through the process. 

<img width="620" alt="Screenshot 2022-06-15 at 12 42 07 AM" src="https://user-images.githubusercontent.com/23524697/174146013-34c1f146-9ca6-44e9-9a56-690761e1b5df.png">

The above error is Xcode 12.4.

Thanks in Advance.

**Comment by SreekanthGudisi** [comment]
Hi, 

I'm trying in Xcode 13 it's not compiling. Here are errors,

```
Multiple commands produce '/Users/datamatics/Library/Developer/Xcode/DerivedData/CFL_FI-esrwjowomlswatbgfwnunkkehaac/Build/Products/UAT Debug-iphonesimulator/MyFIRST PD.app/Frameworks/FMDB.framework':
1) Target 'CFL FI' has copy command from '/Users/datamatics/Library/Developer/Xcode/DerivedData/CFL_FI-esrwjowomlswatbgfwnunkkehaac/SourcePackages/checkouts/SharpsellCore/artifacts/FMDB.xcframework/ios-arm64_i386_x86_64-simulator/FMDB.framework' to '/Users/datamatics/Library/Developer/Xcode/DerivedData/CFL_FI-esrwjowomlswatbgfwnunkkehaac/Build/Products/UAT Debug-iphonesimulator/MyFIRST PD.app/Frameworks/FMDB.framework'
2) That command depends on command in Target 'CFL FI': script phase “[CP] Embed Pods Frameworks”
```
..
```
Multiple commands produce '/Users/datamatics/Library/Developer/Xcode/DerivedData/CFL_FI-esrwjowomlswatbgfwnunkkehaac/Build/Products/UAT Debug-iphonesimulator/MyFIRST PD.app/Frameworks/FBLPromises.framework':
1) Target 'CFL FI' has copy command from '/Users/datamatics/Downloads/Swift package Integration/sharpsell copy/Debug/FBLPromises.xcframework/ios-arm64_i386_x86_64-simulator/FBLPromises.framework' to '/Users/datamatics/Library/Developer/Xcode/DerivedData/CFL_FI-esrwjowomlswatbgfwnunkkehaac/Build/Products/UAT Debug-iphonesimulator/MyFIRST PD.app/Frameworks/FBLPromises.framework'
2) That command depends on command in Target 'CFL FI': script phase “[CP] Embed Pods Frameworks”
```

**Comment by SuryaSharpsell** [comment]
@SreekanthGudisi - We have fixed the swift package manger issue in the newer version. Now you can choose next major version to add a latest Sharpsell SDK to your iOS package, as given below.

<img width="1161" alt="Screenshot 2022-09-26 at 8 49 31 AM" src="https://user-images.githubusercontent.com/93570040/192187441-6b09285f-967b-41a4-b953-7e40333bc4f4.png">
